low_pass_alpha: 0.6
scaling_factor: 1.2
left:
  urdf_path: left_sharpa_wave_6dof.urdf
  target_origin_link: "left_hand_C_MC"
  human_origin_idx: 0
  target_finger_links: ["left_thumb_fingertip", "left_index_fingertip", "left_middle_fingertip", "left_ring_fingertip", "left_pinky_fingertip"]
  human_finger_idxs: [16, 17, 18, 19, 20]
  target_joint_names: [
    "L_forearm_tx_link_joint",
    "L_forearm_ty_link_joint",
    "L_forearm_tz_link_joint",
    "L_forearm_roll_link_joint",
    "L_forearm_pitch_link_joint",
    "L_forearm_yaw_link_joint",
    "left_thumb_CMC_FE",
    "left_thumb_CMC_AA",
    "left_thumb_MCP_FE",
    "left_thumb_MCP_AA",
    "left_thumb_IP",
    "left_index_MCP_FE",
    "left_index_MCP_AA",
    "left_index_PIP",
    "left_index_DIP",
    "left_middle_MCP_FE",
    "left_middle_MCP_AA",
    "left_middle_PIP",
    "left_middle_DIP",
    "left_ring_MCP_FE",
    "left_ring_MCP_AA",
    "left_ring_PIP",
    "left_ring_DIP",
    "left_pinky_CMC",
    "left_pinky_MCP_FE",
    "left_pinky_MCP_AA",
    "left_pinky_PIP",
    "left_pinky_DIP",
  ]
  wrist_body: "left_hand_C_MC"

right:
  urdf_path: right_sharpa_wave_6dof.urdf
  target_origin_link: "right_hand_C_MC"
  human_origin_idx: 0
  target_finger_links: ["right_thumb_fingertip", "right_index_fingertip", "right_middle_fingertip", "right_ring_fingertip", "right_pinky_fingertip"]
  human_finger_idxs: [16, 17, 18, 19, 20]
  target_joint_names: [
    "R_forearm_tx_link_joint",
    "R_forearm_ty_link_joint",
    "R_forearm_tz_link_joint",
    "R_forearm_roll_link_joint",
    "R_forearm_pitch_link_joint",
    "R_forearm_yaw_link_joint",
    "right_thumb_CMC_FE",
    "right_thumb_CMC_AA",
    "right_thumb_MCP_FE",
    "right_thumb_MCP_AA",
    "right_thumb_IP",
    "right_index_MCP_FE",
    "right_index_MCP_AA",
    "right_index_PIP",
    "right_index_DIP",
    "right_middle_MCP_FE",
    "right_middle_MCP_AA",
    "right_middle_PIP",
    "right_middle_DIP",
    "right_ring_MCP_FE",
    "right_ring_MCP_AA",
    "right_ring_PIP",
    "right_ring_DIP",
    "right_pinky_CMC",
    "right_pinky_MCP_FE",
    "right_pinky_MCP_AA",
    "right_pinky_PIP",
    "right_pinky_DIP",
  ]
  wrist_body: "right_hand_C_MC"
